version: '3.8'
services:
  front:
    image: jalvarez/amplify-tutorial:local
    container_name: amplify-tutorial
    build: 
      context: ./
      dockerfile: ./Dockerfile.local
    environment:
      CHOKIDAR_USEPOLLING: "true"      
    ports:
      - 8003:3000
    volumes: 
      - ./src/:/app/src
